# Generated by Django 5.2.9 on 2025-12-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
